### ISSUE TITLE
Demo instructions don't work - setup.py problem

### ISSUE THREAD

**Issue by centralniak** [victorlin/bugbuzz-python#4]
Running `pip install -e .` results in:

On Python 2.7.8:

```
  Running setup.py develop for bugbuzz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/bugbuzz/bugbuzz-py27/setup.py", line 8, in <module>
        import bugbuzz
      File "bugbuzz/__init__.py", line 19, in <module>
        from .packages import pubnub
      File "bugbuzz/packages/__init__.py", line 3, in <module>
        from . import pubnub  # noqa
      File "bugbuzz/packages/pubnub/__init__.py", line 2040, in <module>
        class PubnubHTTPAdapter(HTTPAdapter):
    NameError: name 'HTTPAdapter' is not defined
    Complete output from command /tmp/bugbuzz/bugbuzz-py27/bin/python -c "import setuptools, tokenize; __file__='/tmp/bugbuzz/bugbuzz-py27/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/bugbuzz/bugbuzz-py27/setup.py", line 8, in <module>

    import bugbuzz

  File "bugbuzz/__init__.py", line 19, in <module>

    from .packages import pubnub

  File "bugbuzz/packages/__init__.py", line 3, in <module>

    from . import pubnub  # noqa

  File "bugbuzz/packages/pubnub/__init__.py", line 2040, in <module>

    class PubnubHTTPAdapter(HTTPAdapter):

NameError: name 'HTTPAdapter' is not defined
```

If Python 3 is a requirement I suggest adding this information to the readme as well as setup.py (via Trove Classifiers).

**Comment by guinslym** [comment]
Same bug as @centralniak https://gist.github.com/guinslym/547cf2e77245a5e20871

**Comment by victorlin** [comment]
@centralniak @guinslym I think that's because requests submodule was not cloned, try

```
git clone --recursive git@github.com:victorlin/bugbuzz-python.git
```
